let people=PEOPLE.map(p=>({...p,parents:[...(p.parents||[])]})),zoom=.82,ox=-120,oy=0,editMode=false,photoData="";
const $=id=>document.getElementById(id),full=p=>(p.firstName+" "+p.lastName).trim(),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
if(localStorage.familyTreeDataV2)try{people=JSON.parse(localStorage.familyTreeDataV2)}catch{}
function save(){localStorage.familyTreeDataV2=JSON.stringify(people)}function toast(t){let x=$("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
function gen(){let m=new Map();function g(p,s=new Set()){if(m.has(p.id))return m.get(p.id);if(!p.parents.length||s.has(p.id)){m.set(p.id,0);return 0}let a=p.parents.map(id=>people.find(x=>x.id===id)).filter(Boolean),v=a.length?Math.max(...a.map(x=>g(x,new Set([...s,p.id]))))+1:0;m.set(p.id,v);return v}people.forEach(p=>g(p));return m}
function units(){let used=new Set(),u=[];people.forEach(p=>{if(used.has(p.id))return;let q=p.partnerId&&people.find(x=>x.id===p.partnerId&&x.partnerId===p.id);if(q){u.push([p,q]);used.add(p.id);used.add(q.id)}else{u.push([p]);used.add(p.id)}});return u}
function render(){
 let tree=$("tree");tree.innerHTML="";let g=gen(),us=units(),um=new Map(),levels=new Map();
 us.forEach(u=>{let n=Math.max(...u.map(p=>g.get(p.id)||0));if(!levels.has(n))levels.set(n,[]);levels.get(n).push(u);u.forEach(p=>um.set(p.id,u))});
 let pos=new Map(),Y=185,W=235,H=32;
 [...levels].sort((a,b)=>a[0]-b[0]).forEach(([lev,arr])=>{let widths=arr.map(u=>u.length==2?W*2+H:W),total=widths.reduce((a,b)=>a+b,0)+(arr.length-1)*70,x=-total/2;arr.forEach((u,i)=>{pos.set(u[0].id,{x:x+widths[i]/2,y:lev*Y});x+=widths[i]+70})});
 let svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.classList.add("lines");svg.setAttribute("width",2600);svg.setAttribute("height",(Math.max(...g.values(),0)+2)*Y+180);
 people.forEach(ch=>{if(!ch.parents.length)return;let par=[...new Set(ch.parents.map(id=>um.get(id)).filter(Boolean))],cu=um.get(ch.id);if(!cu||!par.length)return;let cp=pos.get(cu[0].id),ps=par.map(u=>pos.get(u[0].id)).filter(Boolean);let l=Math.min(...ps.map(p=>p.x)),r=Math.max(...ps.map(p=>p.x)),top=Math.max(...ps.map(p=>p.y))+112,bot=cp.y,mid=top+(bot-top)*.45;let path=document.createElementNS("http://www.w3.org/2000/svg","path");path.setAttribute("d",ps.length>1?`M${l} ${top} L${l} ${mid} L${r} ${mid} L${r} ${top} M${(l+r)/2} ${mid} L${cp.x} ${bot}`:`M${ps[0].x} ${ps[0].y+112} L${cp.x} ${bot}`);svg.appendChild(path)});tree.appendChild(svg);
 us.forEach(u=>{let p=pos.get(u[0].id),f=document.createElement("div");f.className="family";f.style.left=p.x+"px";f.style.top=p.y+"px";u.forEach((x,i)=>{let b=document.createElement("button");b.className="node "+(x.gender==="F"?"f":"");b.dataset.id=x.id;let pic=x.photo?`<img src="${esc(x.photo)}">`:`<div class="avatar">${x.gender==="F"?"👩":"👨"}</div>`;let role=x.parents.length?(x.gender==="F"?"MEITA":"DĒLS"):"";b.innerHTML=pic+`<div><div class="n">${esc(full(x))}</div><div class="d">${esc(x.birth||"")}${x.birth&&x.death?" – ":""}${esc(x.death||"")}</div><div class="p">${esc(x.place||"")}</div>${role?`<span class="role">${role}</span>`:""}</div>`;b.onclick=()=>editMode?openEditor(x.id):details(x);f.appendChild(b);if(u.length==2&&i==0){let h=document.createElement("div");h.className="heartbox";h.textContent="♥";f.appendChild(h)}});tree.appendChild(f)});
 transform()}
function transform(){$("tree").style.transform=`translate(${ox}px,${oy}px) scale(${zoom})`;$("reset").textContent=Math.round(zoom*100)+"%"}
function fill(p){$("parents").innerHTML="";$("partner").innerHTML='<option value="">— nav norādīts —</option>';people.filter(x=>x.id!==p?.id).forEach(x=>{$("parents").insertAdjacentHTML("beforeend",`<option value="${x.id}" ${(p?.parents||[]).includes(x.id)?"selected":""}>${esc(full(x))}</option>`);$("partner").insertAdjacentHTML("beforeend",`<option value="${x.id}" ${p?.partnerId===x.id?"selected":""}>${esc(full(x))}</option>`)})}
function openEditor(id=""){let p=id&&people.find(x=>x.id===id);$("pid").value=id;$("title").textContent=p?"Rediģēt personu":"Pievienot personu";$("first").value=p?.firstName||"";$("last").value=p?.lastName||"";$("birth").value=p?.birth||"";$("death").value=p?.death||"";$("gender").value=p?.gender||"";$("place").value=p?.place||"";$("bio").value=p?.bio||"";photoData=p?.photo||"";$("drop").innerHTML=photoData?`<img src="${esc(photoData)}">`:`📷<small>Noklikšķini, lai pievienotu foto</small><input id="photo" type="file" accept="image/*">`;if(!photoData)$("photo").onchange=e=>readPhoto(e.target.files[0]);fill(p);$("panel").classList.remove("hidden")}
function readPhoto(f){if(!f)return;if(f.size>2000000){toast("Foto maksimums 2 MB.");return}let r=new FileReader();r.onload=()=>{photoData=r.result;$("drop").innerHTML=`<img src="${esc(photoData)}">`};r.readAsDataURL(f)}
$("edit").onclick=()=>{editMode=!editMode;$("edit").textContent=editMode?"✓ Rediģēšana":"✎ Rediģēt";$("panel").classList.toggle("hidden",!editMode);render()};$("close").onclick=$("cancel").onclick=()=>$("panel").classList.add("hidden");$("drop").onclick=()=>{let x=$("photo");if(x)x.click()};
$("form").onsubmit=e=>{e.preventDefault();let id=$("pid").value,p=id?people.find(x=>x.id===id):null;if(!p){id="p"+Date.now();p={id,parents:[],partnerId:""};people.push(p)}Object.assign(p,{firstName:$("first").value.trim(),lastName:$("last").value.trim(),birth:$("birth").value.trim(),death:$("death").value.trim(),gender:$("gender").value,place:$("place").value.trim(),bio:$("bio").value.trim(),photo:photoData,parents:[...$("parents").selectedOptions].map(o=>o.value),partnerId:$("partner").value});save();$("panel").classList.add("hidden");render();toast("Persona saglabāta.")};
$("photo").onchange=e=>readPhoto(e.target.files[0]);$("search").oninput=()=>{let q=$("search").value.toLowerCase();document.querySelectorAll(".node").forEach(n=>{let p=people.find(x=>x.id===n.dataset.id);n.classList.toggle("hit",q&&full(p).toLowerCase().includes(q))})};$("plus").onclick=()=>{zoom=Math.min(1.8,zoom+.1);transform()};$("minus").onclick=()=>{zoom=Math.max(.45,zoom-.1);transform()};$("reset").onclick=()=>{zoom=.82;ox=-120;oy=0;transform()};
let drag=0,sx,sy,a,b,v=$("vp");v.onpointerdown=e=>{if(e.target.closest(".node"))return;drag=1;sx=e.clientX;sy=e.clientY;a=ox;b=oy;v.setPointerCapture(e.pointerId)};v.onpointermove=e=>{if(drag){ox=a+e.clientX-sx;oy=b+e.clientY-sy;transform()}};v.onpointerup=()=>drag=0;
function details(p){$("details").innerHTML=`<div class="details">${p.photo?`<img src="${esc(p.photo)}">`:""}<h2>${esc(full(p))}</h2><p><b>Dzimšana:</b> ${esc(p.birth||"—")}<br><b>Miršana:</b> ${esc(p.death||"—")}<br><b>Vieta:</b> ${esc(p.place||"—")}</p><p>${esc(p.bio||"")}</p></div>`;$("dlg").showModal()}$("xd").onclick=()=>$("dlg").close();render();
